/*
 * Banks API
 * Banks OOP project for 1C architecture course.
 *
 * OpenAPI spec version: 1.0
 * Contact: pushin.da@phystech.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ResponseWrapperBank
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-24T08:53:26.331Z[GMT]")
public class ResponseWrapperBank {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("debitPercentage")
  private Double debitPercentage = null;

  @SerializedName("creditCommission")
  private Double creditCommission = null;

  @SerializedName("unverifiedTransactionAmountLimit")
  private Long unverifiedTransactionAmountLimit = null;

  public ResponseWrapperBank id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ResponseWrapperBank debitPercentage(Double debitPercentage) {
    this.debitPercentage = debitPercentage;
    return this;
  }

   /**
   * Get debitPercentage
   * @return debitPercentage
  **/
  @Schema(description = "")
  public Double getDebitPercentage() {
    return debitPercentage;
  }

  public void setDebitPercentage(Double debitPercentage) {
    this.debitPercentage = debitPercentage;
  }

  public ResponseWrapperBank creditCommission(Double creditCommission) {
    this.creditCommission = creditCommission;
    return this;
  }

   /**
   * Get creditCommission
   * @return creditCommission
  **/
  @Schema(description = "")
  public Double getCreditCommission() {
    return creditCommission;
  }

  public void setCreditCommission(Double creditCommission) {
    this.creditCommission = creditCommission;
  }

  public ResponseWrapperBank unverifiedTransactionAmountLimit(Long unverifiedTransactionAmountLimit) {
    this.unverifiedTransactionAmountLimit = unverifiedTransactionAmountLimit;
    return this;
  }

   /**
   * Get unverifiedTransactionAmountLimit
   * @return unverifiedTransactionAmountLimit
  **/
  @Schema(description = "")
  public Long getUnverifiedTransactionAmountLimit() {
    return unverifiedTransactionAmountLimit;
  }

  public void setUnverifiedTransactionAmountLimit(Long unverifiedTransactionAmountLimit) {
    this.unverifiedTransactionAmountLimit = unverifiedTransactionAmountLimit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperBank responseWrapperBank = (ResponseWrapperBank) o;
    return Objects.equals(this.id, responseWrapperBank.id) &&
        Objects.equals(this.debitPercentage, responseWrapperBank.debitPercentage) &&
        Objects.equals(this.creditCommission, responseWrapperBank.creditCommission) &&
        Objects.equals(this.unverifiedTransactionAmountLimit, responseWrapperBank.unverifiedTransactionAmountLimit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, debitPercentage, creditCommission, unverifiedTransactionAmountLimit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperBank {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    debitPercentage: ").append(toIndentedString(debitPercentage)).append("\n");
    sb.append("    creditCommission: ").append(toIndentedString(creditCommission)).append("\n");
    sb.append("    unverifiedTransactionAmountLimit: ").append(toIndentedString(unverifiedTransactionAmountLimit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
