/*
 * Banks API
 * Banks OOP project for 1C architecture course.
 *
 * OpenAPI spec version: 1.0
 * Contact: pushin.da@phystech.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.LocalDate;
/**
 * ResponseWrapperDepositAccount
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-24T10:52:54.557Z[GMT]")
public class ResponseWrapperDepositAccount {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("bankId")
  private Long bankId = null;

  @SerializedName("ownerId")
  private Long ownerId = null;

  @SerializedName("currentAmount")
  private Long currentAmount = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    CREDIT("CREDIT"),
    DEBIT("DEBIT"),
    DEPOSIT("DEPOSIT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return TypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("type")
  private TypeEnum type = null;

  @SerializedName("balancePercentage")
  private Double balancePercentage = null;

  @SerializedName("accumulatedAmount")
  private Long accumulatedAmount = null;

  @SerializedName("upToDate")
  private LocalDate upToDate = null;

  public ResponseWrapperDepositAccount id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ResponseWrapperDepositAccount bankId(Long bankId) {
    this.bankId = bankId;
    return this;
  }

   /**
   * Get bankId
   * @return bankId
  **/
  @Schema(description = "")
  public Long getBankId() {
    return bankId;
  }

  public void setBankId(Long bankId) {
    this.bankId = bankId;
  }

  public ResponseWrapperDepositAccount ownerId(Long ownerId) {
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Get ownerId
   * @return ownerId
  **/
  @Schema(description = "")
  public Long getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(Long ownerId) {
    this.ownerId = ownerId;
  }

  public ResponseWrapperDepositAccount currentAmount(Long currentAmount) {
    this.currentAmount = currentAmount;
    return this;
  }

   /**
   * Get currentAmount
   * @return currentAmount
  **/
  @Schema(description = "")
  public Long getCurrentAmount() {
    return currentAmount;
  }

  public void setCurrentAmount(Long currentAmount) {
    this.currentAmount = currentAmount;
  }

  public ResponseWrapperDepositAccount type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public ResponseWrapperDepositAccount balancePercentage(Double balancePercentage) {
    this.balancePercentage = balancePercentage;
    return this;
  }

   /**
   * Get balancePercentage
   * @return balancePercentage
  **/
  @Schema(description = "")
  public Double getBalancePercentage() {
    return balancePercentage;
  }

  public void setBalancePercentage(Double balancePercentage) {
    this.balancePercentage = balancePercentage;
  }

  public ResponseWrapperDepositAccount accumulatedAmount(Long accumulatedAmount) {
    this.accumulatedAmount = accumulatedAmount;
    return this;
  }

   /**
   * Get accumulatedAmount
   * @return accumulatedAmount
  **/
  @Schema(description = "")
  public Long getAccumulatedAmount() {
    return accumulatedAmount;
  }

  public void setAccumulatedAmount(Long accumulatedAmount) {
    this.accumulatedAmount = accumulatedAmount;
  }

  public ResponseWrapperDepositAccount upToDate(LocalDate upToDate) {
    this.upToDate = upToDate;
    return this;
  }

   /**
   * Get upToDate
   * @return upToDate
  **/
  @Schema(description = "")
  public LocalDate getUpToDate() {
    return upToDate;
  }

  public void setUpToDate(LocalDate upToDate) {
    this.upToDate = upToDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseWrapperDepositAccount responseWrapperDepositAccount = (ResponseWrapperDepositAccount) o;
    return Objects.equals(this.id, responseWrapperDepositAccount.id) &&
        Objects.equals(this.bankId, responseWrapperDepositAccount.bankId) &&
        Objects.equals(this.ownerId, responseWrapperDepositAccount.ownerId) &&
        Objects.equals(this.currentAmount, responseWrapperDepositAccount.currentAmount) &&
        Objects.equals(this.type, responseWrapperDepositAccount.type) &&
        Objects.equals(this.balancePercentage, responseWrapperDepositAccount.balancePercentage) &&
        Objects.equals(this.accumulatedAmount, responseWrapperDepositAccount.accumulatedAmount) &&
        Objects.equals(this.upToDate, responseWrapperDepositAccount.upToDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, bankId, ownerId, currentAmount, type, balancePercentage, accumulatedAmount, upToDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseWrapperDepositAccount {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    bankId: ").append(toIndentedString(bankId)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    currentAmount: ").append(toIndentedString(currentAmount)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    balancePercentage: ").append(toIndentedString(balancePercentage)).append("\n");
    sb.append("    accumulatedAmount: ").append(toIndentedString(accumulatedAmount)).append("\n");
    sb.append("    upToDate: ").append(toIndentedString(upToDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
