/*
 * Banks API
 * Banks OOP project for 1C architecture course.
 *
 * OpenAPI spec version: 1.0
 * Contact: pushin.da@phystech.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.threeten.bp.LocalDate;
import io.swagger.client.model.ResponseWrapperDepositAccount;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AccountApi
 */
@Ignore
public class AccountApiTest {

    private final AccountApi api = new AccountApi();

    /**
     * 
     *
     * Creates bank deposit account for client with {clientId} 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createDepositTest() throws Exception {
        Long clientId = null;
        LocalDate upToDate = null;
        ResponseWrapperDepositAccount response = api.createDeposit(clientId, upToDate);

        // TODO: test validations
    }
}
