/*
 * Banks API
 * Banks OOP project for 1C architecture course.
 *
 * OpenAPI spec version: 1.0
 * Contact: pushin.da@phystech.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ResponseWrapperBank;
import io.swagger.client.model.ResponseWrapperListBaseAccount;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for BankApi
 */
@Ignore
public class BankApiTest {

    private final BankApi api = new BankApi();

    /**
     * 
     *
     * Creates new bank
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createBankTest() throws Exception {
        Double debitPercentage = null;
        Double creditCommission = null;
        Long unverifiedAmountLimit = null;
        ResponseWrapperBank response = api.createBank(debitPercentage, creditCommission, unverifiedAmountLimit);

        // TODO: test validations
    }
    /**
     * 
     *
     * Lists all bank accounts
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBankAccountsTest() throws Exception {
        Long bankId = null;
        ResponseWrapperListBaseAccount response = api.getBankAccounts(bankId);

        // TODO: test validations
    }
}
