/*
 * Banks API
 * Banks OOP project for 1C architecture course.
 *
 * OpenAPI spec version: 1.0
 * Contact: pushin.da@phystech.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Client;
import io.swagger.client.model.ResponseWrapperClientWrapper;
import io.swagger.client.model.ResponseWrapperListClient;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ClientApi
 */
@Ignore
public class ClientApiTest {

    private final ClientApi api = new ClientApi();

    /**
     * 
     *
     * Creates a new client in bank with {bankId}
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addClientTest() throws Exception {
        Long bankId = null;
        String firstName = null;
        String secondName = null;
        ResponseWrapperClientWrapper response = api.addClient(bankId, firstName, secondName);

        // TODO: test validations
    }
    /**
     * 
     *
     * Edits client with {clientID} in bank
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void editClientTest() throws Exception {
        Client body = null;
        Long clientId = null;
        ResponseWrapperClientWrapper response = api.editClient(body, clientId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Get clients of bank with {bankId}
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBankClientsTest() throws Exception {
        Long bankId = null;
        ResponseWrapperListClient response = api.getBankClients(bankId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Get client info
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getClientTest() throws Exception {
        Long clientId = null;
        ResponseWrapperClientWrapper response = api.getClient(clientId);

        // TODO: test validations
    }
}
