/*
 * Banks API
 * Banks OOP project for 1C architecture course.
 *
 * OpenAPI spec version: 1.0
 * Contact: pushin.da@phystech.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ResponseWrapperListTransaction;
import io.swagger.client.model.ResponseWrapperTransaction;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for TransactionApi
 */
@Ignore
public class TransactionApiTest {

    private final TransactionApi api = new TransactionApi();

    /**
     * 
     *
     * lists all transactions made by user
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAllTransactionsByCreatorIdTest() throws Exception {
        Long creatorClientId = null;
        ResponseWrapperListTransaction response = api.getAllTransactionsByCreatorId(creatorClientId);

        // TODO: test validations
    }
    /**
     * 
     *
     * Creates a new transaction authorized by {clientId}
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void transferTest() throws Exception {
        Long clientId = null;
        Long sourceAccountId = null;
        Long targetAccountId = null;
        String currency = null;
        Long amount = null;
        ResponseWrapperTransaction response = api.transfer(clientId, sourceAccountId, targetAccountId, currency, amount);

        // TODO: test validations
    }
}
