/*
 * Banks API
 * Banks OOP project for 1C architecture course.
 *
 * OpenAPI spec version: 1.0
 * Contact: pushin.da@phystech.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.ResponseWrapperBank;
import io.swagger.client.model.ResponseWrapperListBaseAccount;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BankApi {
    private ApiClient apiClient;

    public BankApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BankApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for createBank
     * @param debitPercentage  (required)
     * @param creditCommission  (required)
     * @param unverifiedAmountLimit  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createBankCall(Double debitPercentage, Double creditCommission, Long unverifiedAmountLimit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/bank/create";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (debitPercentage != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("debit_percentage", debitPercentage));
        if (creditCommission != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("credit_commission", creditCommission));
        if (unverifiedAmountLimit != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("unverified_amount_limit", unverifiedAmountLimit));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createBankValidateBeforeCall(Double debitPercentage, Double creditCommission, Long unverifiedAmountLimit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'debitPercentage' is set
        if (debitPercentage == null) {
            throw new ApiException("Missing the required parameter 'debitPercentage' when calling createBank(Async)");
        }
        // verify the required parameter 'creditCommission' is set
        if (creditCommission == null) {
            throw new ApiException("Missing the required parameter 'creditCommission' when calling createBank(Async)");
        }
        // verify the required parameter 'unverifiedAmountLimit' is set
        if (unverifiedAmountLimit == null) {
            throw new ApiException("Missing the required parameter 'unverifiedAmountLimit' when calling createBank(Async)");
        }
        
        com.squareup.okhttp.Call call = createBankCall(debitPercentage, creditCommission, unverifiedAmountLimit, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * Creates new bank
     * @param debitPercentage  (required)
     * @param creditCommission  (required)
     * @param unverifiedAmountLimit  (required)
     * @return ResponseWrapperBank
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ResponseWrapperBank createBank(Double debitPercentage, Double creditCommission, Long unverifiedAmountLimit) throws ApiException {
        ApiResponse<ResponseWrapperBank> resp = createBankWithHttpInfo(debitPercentage, creditCommission, unverifiedAmountLimit);
        return resp.getData();
    }

    /**
     * 
     * Creates new bank
     * @param debitPercentage  (required)
     * @param creditCommission  (required)
     * @param unverifiedAmountLimit  (required)
     * @return ApiResponse&lt;ResponseWrapperBank&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ResponseWrapperBank> createBankWithHttpInfo(Double debitPercentage, Double creditCommission, Long unverifiedAmountLimit) throws ApiException {
        com.squareup.okhttp.Call call = createBankValidateBeforeCall(debitPercentage, creditCommission, unverifiedAmountLimit, null, null);
        Type localVarReturnType = new TypeToken<ResponseWrapperBank>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Creates new bank
     * @param debitPercentage  (required)
     * @param creditCommission  (required)
     * @param unverifiedAmountLimit  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createBankAsync(Double debitPercentage, Double creditCommission, Long unverifiedAmountLimit, final ApiCallback<ResponseWrapperBank> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createBankValidateBeforeCall(debitPercentage, creditCommission, unverifiedAmountLimit, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ResponseWrapperBank>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getBankAccounts
     * @param bankId  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getBankAccountsCall(Long bankId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/bank/{bankId}/accounts"
            .replaceAll("\\{" + "bankId" + "\\}", apiClient.escapeString(bankId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getBankAccountsValidateBeforeCall(Long bankId, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'bankId' is set
        if (bankId == null) {
            throw new ApiException("Missing the required parameter 'bankId' when calling getBankAccounts(Async)");
        }
        
        com.squareup.okhttp.Call call = getBankAccountsCall(bankId, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * 
     * Lists all bank accounts
     * @param bankId  (required)
     * @return ResponseWrapperListBaseAccount
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ResponseWrapperListBaseAccount getBankAccounts(Long bankId) throws ApiException {
        ApiResponse<ResponseWrapperListBaseAccount> resp = getBankAccountsWithHttpInfo(bankId);
        return resp.getData();
    }

    /**
     * 
     * Lists all bank accounts
     * @param bankId  (required)
     * @return ApiResponse&lt;ResponseWrapperListBaseAccount&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<ResponseWrapperListBaseAccount> getBankAccountsWithHttpInfo(Long bankId) throws ApiException {
        com.squareup.okhttp.Call call = getBankAccountsValidateBeforeCall(bankId, null, null);
        Type localVarReturnType = new TypeToken<ResponseWrapperListBaseAccount>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     *  (asynchronously)
     * Lists all bank accounts
     * @param bankId  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getBankAccountsAsync(Long bankId, final ApiCallback<ResponseWrapperListBaseAccount> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getBankAccountsValidateBeforeCall(bankId, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<ResponseWrapperListBaseAccount>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
